### ISSUE TITLE
websocket on v4

### ISSUE THREAD

**Issue by crotwell** [EarthScope/ringserver#59]
Was trying to test the new seedlink4 on ringserver v4. Using the default ring.conf in the doc.

Web access works, for example this does show data in the ringserver:
```
http://localhost:18000/streams
```

but if I try to use seedlink 3 (or 4) over websocket, I get a fail. Javascript console shows:
```
GET ws://127.0.0.1:18000/
Status 404 Not Found
Version HTTP/1.1
Transferred 91 B (0 B size)
DNS ResolutionSystem
```

Exact same code, works when connecting to a ringserver v3 over websocket. Any chance something broke the websocket support in v4?

See tutorial7 here for more or less the javascript code being used:
https://crotwell.github.io/seisplotjs/tutorial/7_realtime.html

**Comment by crotwell** [comment]
Just to clarify the ringserver conf, I have:
```
ListenPort 18000
```
which I believe should imply seedlink over websocket should work.

Setting verbose to 3 on ringserver gives:
```
Wed Dec 04 10:20:42 2024 - ringserver version: 4.0.0
Wed Dec 04 10:20:42 2024 - Starting signal handling thread
Wed Dec 04 10:20:42 2024 - Recovering existing ring packet buffer file
Wed Dec 04 10:20:42 2024 - Memory-mapping ring packet buffer file
Wed Dec 04 10:20:42 2024 - Recovering stream index
Wed Dec 04 10:20:42 2024 - Ring initialized
Wed Dec 04 10:20:42 2024 - Ring parameters, version: 2, start: 2024-12-04T15:20:42.490135Z
Wed Dec 04 10:20:42 2024 -    ringsize: 1073741824 (1.0 GiB), pktsize: 632 (512 payload)
Wed Dec 04 10:20:42 2024 -    headersize: 16384
Wed Dec 04 10:20:42 2024 -    maxpackets: 1698932, maxoffset: 1073724392
Wed Dec 04 10:20:42 2024 -    streamcount: 1
Wed Dec 04 10:20:42 2024 -    volatile: no, mmap: yes, corrupt: no, flux: no
Wed Dec 04 10:20:42 2024 -    earliest packet ID: 1, offset: 0
Wed Dec 04 10:20:42 2024 -    earliest packet creation time: 2024-12-04T15:00:06.045259Z
Wed Dec 04 10:20:42 2024 -    earliest packet data start time: 2024-12-04T14:59:15.009999Z
Wed Dec 04 10:20:42 2024 -    latest packet ID: 113, offset: 70784
Wed Dec 04 10:20:42 2024 -    latest packet creation time: 2024-12-04T15:04:13.220569Z
Wed Dec 04 10:20:42 2024 -    latest packet data start time: 2024-12-04T15:03:54.059999Z
Wed Dec 04 10:20:42 2024 - Server parameters:
Wed Dec 04 10:20:42 2024 -    server ID: Ring Server
Wed Dec 04 10:20:42 2024 -    ring directory: /Users/crotwell/Code/GitHub/iris-edu/ringserver/ring
Wed Dec 04 10:20:42 2024 -    max clients: 600
Wed Dec 04 10:20:42 2024 -    max clients per IP: 0
Wed Dec 04 10:20:42 2024 -    configuration file: doc/ring.conf
Wed Dec 04 10:20:42 2024 -    client timeout: 3600 seconds
Wed Dec 04 10:20:42 2024 -    time window limit: 100%
Wed Dec 04 10:20:42 2024 -    resolve hostnames: yes
Wed Dec 04 10:20:42 2024 -    auto recovery: 1
Wed Dec 04 10:20:42 2024 -    TLS certificate file: NONE
Wed Dec 04 10:20:42 2024 -    TLS key file: NONE
Wed Dec 04 10:20:42 2024 -    TLS verify client certificate: no
Wed Dec 04 10:20:42 2024 -    web root: NONE
Wed Dec 04 10:20:42 2024 -    HTTP headers: NONE
Wed Dec 04 10:20:42 2024 -    miniSEED archive: NONE
Wed Dec 04 10:20:42 2024 -    miniSEED idle file timeout: 300 seconds
Wed Dec 04 10:20:42 2024 -    transfer log: NONE
Wed Dec 04 10:20:42 2024 -    limit IP: NONE
Wed Dec 04 10:20:42 2024 -    match IP range: NONE
Wed Dec 04 10:20:42 2024 -    reject IP range: NONE
Wed Dec 04 10:20:42 2024 -    write IP range: 127.0.0.1/255.255.255.255
Wed Dec 04 10:20:42 2024 -    write IP range: ::1/::255.255.255.255
Wed Dec 04 10:20:42 2024 -    trusted IP range: 127.0.0.1/255.255.255.255
Wed Dec 04 10:20:42 2024 -    trusted IP range: ::1/::255.255.255.255
Wed Dec 04 10:20:42 2024 - Server thread (Listen) not running
Wed Dec 04 10:20:42 2024 - Starting Listen listen thread for port 18000
Wed Dec 04 10:20:42 2024 - Server thread (Listen) not running
Wed Dec 04 10:20:42 2024 - Starting Listen listen thread for port 18000
Wed Dec 04 10:20:42 2024 - Listening for connections on port 18000 (IPv4: DataLink SeedLink HTTP)
Wed Dec 04 10:20:42 2024 - Client connections: 0
Wed Dec 04 10:20:42 2024 - Listening for connections on port 18000 (IPv6: DataLink SeedLink HTTP)
Wed Dec 04 10:20:43 2024 - Server thread (Listen) 6164721664 state: ACTIVE
Wed Dec 04 10:20:43 2024 - Server thread (Listen) 6165295104 state: ACTIVE

...

Wed Dec 04 10:20:48 2024 - Server thread (Listen) 6165295104 state: ACTIVE
Wed Dec 04 10:20:48 2024 - Client connections: 0
Wed Dec 04 10:20:48 2024 - Incoming connection: 127.0.0.1 port 60949
Wed Dec 04 10:20:48 2024 - Client connected [18000]: localhost [127.0.0.1] port 60949
Wed Dec 04 10:20:48 2024 - [localhost] Received HTTP request /
Wed Dec 04 10:20:48 2024 - [localhost] Received HTTP request for /
Wed Dec 04 10:20:48 2024 - Client disconnected: localhost
```

**Comment by crotwell** [comment]
Sorry, never mind, I think this was a local firewall/browser issue. I was able to get around it and websocket connection seems to be working.

**Comment by crotwell** [comment]
Weeeeell, maybe I spoke too soon. There might have been a firewall/web browser issue, but still having difficulties getting websocket to work.

On a linux machine (so no pesky firewall issues), I have both a ringserver v4 and the older 2020.075 running each with a simple ListenPort with no other options beyond the ports. Like
```
ListenPort 6371
``` 

Then using my simpledali python code here:
https://github.com/crotwell/simpledali
I am testing just a ID datalink command (see example/getid.py) to the ListenPort, first via a regular datalink socket and then via a websocket datalink.

Here is verbose output from ringserver v4, the important line is probably `Error verifying DataLink sequence bytes (?')`.  The chars in the parenthesis seem to change randomly as I rerun the getid script.

Note that the regular socket to v4 seems to work fine and if I run the same python script connecting to the v2020.075 ringserver, then both regular and web sockets work fine. I presume there is no change to the datalink protocol, at least just sending the ID command. The python gives an error of:
```
ConnectionResetError: [Errno 54] Connection reset by peer
```
which then causes a:
```
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```
which I think means that ringserver is dropping the connection without the sending a Close frame before killing the connection. Guessing you kill with extreme prejudice on error, so maybe that is not actually useful information. I would lean towards sending a websocket Close even in the case of error, but opinions may differ.

```
bin/ringserver_v4 -vv /data/scsn/conf/ringserver_4.conf 
Thu Dec 05 14:37:09 2024 - ringserver version: 4.0.0
Thu Dec 05 14:37:09 2024 - Reading configuration from /data/scsn/conf/ringserver_4.conf
Thu Dec 05 14:37:09 2024 - Starting signal handling thread
Thu Dec 05 14:37:09 2024 - Recovering existing ring packet buffer file
Thu Dec 05 14:37:09 2024 - Allocating ring packet buffer memory
Thu Dec 05 14:37:09 2024 - Reading ring packet buffer file into memory
Thu Dec 05 14:37:09 2024 - Recovering stream index
Thu Dec 05 14:37:09 2024 - Ring initialized
Thu Dec 05 14:37:09 2024 - Ring parameters, version: 2, start: 2024-12-05T14:37:09.912948Z
Thu Dec 05 14:37:09 2024 -    ringsize: 1073741824 (1.0 GiB), pktsize: 632 (512 payload)
Thu Dec 05 14:37:09 2024 -    headersize: 4096
Thu Dec 05 14:37:09 2024 -    maxpackets: 1698952, maxoffset: 1073737032
Thu Dec 05 14:37:09 2024 -    streamcount: 9
Thu Dec 05 14:37:09 2024 -    volatile: no, mmap: no, corrupt: no, flux: no
Thu Dec 05 14:37:09 2024 -    earliest packet ID: 1, offset: 0
Thu Dec 05 14:37:09 2024 -    earliest packet creation time: 2024-12-05T13:22:07.456885Z
Thu Dec 05 14:37:09 2024 -    earliest packet data start time: 2024-12-05T13:22:02.735000Z
Thu Dec 05 14:37:09 2024 -    latest packet ID: 4810, offset: 3039288
Thu Dec 05 14:37:09 2024 -    latest packet creation time: 2024-12-05T13:50:20.619334Z
Thu Dec 05 14:37:09 2024 -    latest packet data start time: 2024-12-05T13:50:15.865000Z
Thu Dec 05 14:37:09 2024 - Server parameters:
Thu Dec 05 14:37:09 2024 -    server ID: Test Ring Server 4
Thu Dec 05 14:37:09 2024 -    ring directory: /data/scsn/ring_4
Thu Dec 05 14:37:09 2024 -    max clients: 600
Thu Dec 05 14:37:09 2024 -    max clients per IP: 0
Thu Dec 05 14:37:09 2024 -    configuration file: /data/scsn/conf/ringserver_4.conf
Thu Dec 05 14:37:09 2024 -    client timeout: 3600 seconds
Thu Dec 05 14:37:09 2024 -    time window limit: 100%
Thu Dec 05 14:37:09 2024 -    resolve hostnames: yes
Thu Dec 05 14:37:09 2024 -    auto recovery: 1
Thu Dec 05 14:37:09 2024 -    TLS certificate file: NONE
Thu Dec 05 14:37:09 2024 -    TLS key file: NONE
Thu Dec 05 14:37:09 2024 -    TLS verify client certificate: no
Thu Dec 05 14:37:09 2024 - Server thread (Listen) not running
Thu Dec 05 14:37:09 2024 - Starting Listen listen thread for port 6371
Thu Dec 05 14:37:09 2024 - Server thread (Listen) not running
Thu Dec 05 14:37:09 2024 - Starting Listen listen thread for port 6371
Thu Dec 05 14:37:09 2024 - Server thread (Listen) not running
Thu Dec 05 14:37:09 2024 - Starting Listen listen thread for port 16001
Thu Dec 05 14:37:09 2024 - Listening for connections on port 6371 (IPv4: DataLink SeedLink HTTP)
Thu Dec 05 14:37:09 2024 - Server thread (Listen) not running
Thu Dec 05 14:37:09 2024 - Starting Listen listen thread for port 16001
Thu Dec 05 14:37:09 2024 - Listening for connections on port 16001 (IPv4: DataLink)
Thu Dec 05 14:37:09 2024 - Listening for connections on port 6371 (IPv6: DataLink SeedLink HTTP)
Thu Dec 05 14:37:09 2024 - Listening for connections on port 16001 (IPv6: DataLink)
Thu Dec 05 14:37:15 2024 - Incoming connection: 10.35.217.194 port 64137
Thu Dec 05 14:37:15 2024 - Client connected [6371]: 10.35.217.194 [10.35.217.194] port 64137
Thu Dec 05 14:37:15 2024 - [10.35.217.194] Received ID (simpleDali:dragrace:0:python)
Thu Dec 05 14:37:15 2024 - Client disconnected: 10.35.217.194
Thu Dec 05 14:37:15 2024 - Incoming connection: 10.35.217.194 port 64138
Thu Dec 05 14:37:15 2024 - Client connected [6371]: 10.35.217.194 [10.35.217.194] port 64138
Thu Dec 05 14:37:15 2024 - [10.35.217.194] Received HTTP request /datalink
Thu Dec 05 14:37:15 2024 - [10.35.217.194] Received WebSocket DataLink request
Thu Dec 05 14:37:15 2024 - [10.35.217.194] Error verifying DataLink sequence bytes (?')
Thu Dec 05 14:37:15 2024 - Client disconnected: 10.35.217.194
```

Here is output from successful getid.py connecting to the older v2020.075 ringserver, both regular and web socket:
```

Attempt regular socket datalink:
connect eeyore.seis.sc.edu:6382
writeCommand: cmd: ID simpleDali:dragrace:0:python dataStr: None
send pre DL as b'DL'31
send head ID simpleDali:dragrace:0:python
drained
Connect to eeyore.seis.sc.edu:6382 via regular socket
Socket Id: DataLink 2020.075 :: DLPROTO:1.0 PACKETSIZE:512

Attempt web socket datalink:
connect ws://eeyore.seis.sc.edu:6382/datalink
Websocket connect to ws://eeyore.seis.sc.edu:6382/datalink
writeCommand: cmd: ID simpleDali:dragrace:0:python dataStr: None
sent DL31 ID simpleDali:dragrace:0:python
parseRespone header: b'ID DataLink 2020.075 :: DLPROTO:1.0 PACKETSIZE:512'
Connect to ws://eeyore.seis.sc.edu:6382/datalink via websocket
WebSocket Id: DataLink 2020.075 :: DLPROTO:1.0 PACKETSIZE:512
```

and here is the output of getid to the new v4 ringserver:
```
Attempt regular socket datalink:
connect eeyore.seis.sc.edu:6371
writeCommand: cmd: ID simpleDali:dragrace:0:python dataStr: None
send pre DL as b'DL'31
send head ID simpleDali:dragrace:0:python
drained
Connect to eeyore.seis.sc.edu:6371 via regular socket
Socket Id: DataLink v1.1 (RingServer/4.0.0) :: DLPROTO:1.1 PACKETSIZE:512

Attempt web socket datalink:
connect ws://eeyore.seis.sc.edu:6371/datalink
Websocket connect to ws://eeyore.seis.sc.edu:6371/datalink
writeCommand: cmd: ID simpleDali:dragrace:0:python dataStr: None
sent DL31 ID simpleDali:dragrace:0:python
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/asyncio/selector_events.py", line 862, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/crotwell/Code/seis/simpledali/example/getid.py", line 30, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/crotwell/Code/seis/simpledali/example/getid.py", line 26, in main
    serverId = await dali.id(programname, username, processid, architecture)
  File "/Users/crotwell/Code/seis/simpledali/src/simpledali/abstractdali.py", line 252, in id
    r = await self.writeCommand(header, None)
  File "/Users/crotwell/Code/seis/simpledali/src/simpledali/abstractdali.py", line 219, in writeCommand
    r = await self.parseResponse()
  File "/Users/crotwell/Code/seis/simpledali/src/simpledali/websocketdali.py", line 67, in parseResponse
    response = await self.ws.recv()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/simpledali/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by crotwell** [comment]
Sounds like this is same issue as #60

**Comment by crotwell** [comment]
dup of #60
